version: '3.3'

services:
  aic_nginx:
    image: nginx:latest
    container_name: aic_nginx_cont
    restart: always
    ports:
      - 2018:2018
      - 80:80
      - 443:443
    volumes:
      - ./static/root:/static/root/static
      - /var/log/aic_site:/var/log/aic_site
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - aic_web
  aic_web:
    build: .
    container_name: aic_web_cont
    restart: always
    command: bash -c "cd .. && python3 manage.py makemigrations && python3 manage.py migrate && export DJANGO_SETTINGS_MODULE='aic_site.settings.production' && gunicorn aic_site.wsgi -b 0.0.0.0:8000 -w 4"
    depends_on:
      - aic_db
    expose:
      - 8000
  aic_db:
    image: postgres:latest
    container_name: aic_db_cont
    restart: always
    volumes:
      - ../Database:/var/lib/postgresql/data
