version: '3.3'

services:
  aic_nginx:
    image: nginx:latest
    container_name: aic_nginx_cont
    restart: always
    ports:
      - 2018:2018
      - 80:80
      - 443:443
    volumes:
      - ./static/root:/static/root/static
      - ../media/root:/static/root/media
      - /var/log/aic_site:/var/log/aic_site
      - /var/log/aic_site/nginx/:/var/log/nginx/
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../lets_encrypt/www:/var/www/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt

    depends_on:
      - aic_web
  aic_web:
    build: .
    container_name: aic_web_cont
    restart: always
    command: bash -c "redis-server & celery -A aic_site worker -l info & cd .. && python3 manage.py migrate && python3 manage.py compilemessages && python3 manage.py collectstatic <<< yes && gunicorn -b 0.0.0.0:8000 --workers=4 aic_site.wsgi"
    volumes:
      - ./static/root:/root/aic_site/static/root
      - ../media/root:/root/aic_site/media
      - ./patches:/patches
      - /var/log/aic_site:/var/log/aic_site
    depends_on:
      - aic_db
    expose:
      - 8000
  aic_db:
    image: postgres:latest
    container_name: aic_db_cont
    restart: always
    volumes:
      - ../Database:/var/lib/postgresql/data
      - ../Database_backup:/Database_backup
