version: '3.3'

services:
  aic_test_nginx:
    image: nginx:latest
    container_name: aic_test_nginx_cont
    restart: always
    ports:
      - 2016:2016
    volumes:
      - ./static/root:/static/root/static
      - ../media_test/root:/static/root/media
      - /var/log/aic_test_site:/var/log/aic_test_site
      - /var/log/aic_test_site/nginx/:/var/log/nginx/
      - ./config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx/sites-available:/etc/nginx/sites-available
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - aic_test_web
  aic_test_web:
    build: .
    container_name: aic_test_web_cont
    restart: always
    command: bash -c "apt-get update && \
                      apt-get install software-properties-common && \
                      add-apt-repository ppa:jonathonf/python-3.6 && \
                      apt-get update && \
                      apt-get install python3.6 && \
                      rm /usr/bin/python3 && \
                      ln -s /usr/bin/python3.6 /usr/bin/python3 && \
                      cd .. && \
                      python3 manage.py migrate && \
                      python3 manage.py compilemessages && \
                      python3 manage.py collectstatic <<< yes && \
                      gunicorn -b 0.0.0.0:8000 --workers=4 aic_site.wsgi"
    volumes:
      - ./static/root:/root/aic_site/static/root
      - ../media_test/root:/root/aic_site/media
      - /var/log/aic_test_site:/var/log/aic_site
    depends_on:
      - aic_test_db
    expose:
      - 8000
  aic_test_db:
    image: postgres:latest
    container_name: aic_test_db_cont
    restart: always
    volumes:
      - ../Database_test:/var/lib/postgresql/data
      - ../Database_test_backup:/Database_backup
      - ../Database_backup:/Database_backup_production
